### ISSUE TITLE
"ProviderError: invalid sender" on all RPCs except for one

### ISSUE THREAD

**Issue by ramicaza** [nomiclabs/hardhat#1828]
I am trying to deploy a smart contract to the polygon network like so:

```
const NFT = await hre.ethers.getContractFactory("NFT");
  const nft = await NFT.deploy("The NFT", "NFT", `https://blah.com`);
  await nft.deployed();
```

however I am getting the following error:

```
ProviderError: invalid sender
    at HttpProvider.request (/<path>/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/<path>/node_modules/hardhat/src/internal/core/providers/accounts.ts:167:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EthersProviderWrapper.send (/<path>/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

It's extremely frustrating because it randomly broke and I only just noticed today.  I figured that since we didn't change any of our code, it must have been a change on the RPC side.  So I tried different RPCs and it turns out that now, the only one that works is the chainstacklabs rpc for the polygon network.  https://matic-mumbai.chainstacklabs.com

I think it's only a matter of time before this last RPC also gets updated and we are unable to deploy our smart contracts

**Comment by rodsotdia** [comment]
I'm having the same issues with all RPC URLs for Mumbai Testnet throwing the `invalid sender` error. Putting the `gasPrice: 8000000000` resolves the issue in the meantime.

**Comment by fvictorio** [comment]
We just published [`hardhat@2.6.2`](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.6.2) which should fix this issue. Please let us know if it doesn't!

**Comment by ethernetweb** [comment]
> We just published [`hardhat@2.6.2`](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.6.2) which should fix this issue. Please let us know if it doesn't!

It does not, in my case. It still hangs permanently, does not generate a txn id. --verbose does not provide any valuable output for reason of failure.
I have tried all the fixes provided to no avail. I have used multiple RPC endpoints, etc.

**Comment by fvictorio** [comment]
> It does not, in my case. It still hangs permanently, does not generate a txn id. --verbose does not provide any valuable output for reason of failure.
I have tried all the fixes provided to no avail. I have used multiple RPC endpoints, etc.

My comment refers specifically to the "invalid sender" thing. What you mention seems to be a different problem. 
If that's the case and you have a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) you can share., please submit a new issue.

**Comment by max-marcus** [comment]
> > We just published [`hardhat@2.6.2`](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.6.2) which should fix this issue. Please let us know if it doesn't!
> 
> It does not, in my case. It still hangs permanently, does not generate a txn id. --verbose does not provide any valuable output for reason of failure.
> I have tried all the fixes provided to no avail. I have used multiple RPC endpoints, etc.

Confirmed fixed for me. Thanks

**Comment by aspiers** [comment]
[**@fvictorio**](https://github.com/fvictorio) commented on [August 31, 2021 5:05 PM](https://github.com/nomiclabs/hardhat/issues/1828#issuecomment-909373344 "2021-08-31T16:05:22Z - Replied by Github Reply Comments"):
> We just published [`hardhat@2.6.2`](https://github.com/nomiclabs/hardhat/releases/tag/hardhat%402.6.2) which should fix this issue. Please let us know if it doesn't!

With 2.6.4 I don't get this error, although I get various other issues relating to gas fees.  Please can you reference the exact PR and/or commit which was supposed to fix it?  I'm guessing it was #1841?
